export const GET_USER_LIST_SUGGESTIONS = 'GET_USER_LIST_SUGGESTIONS';
export const GET_USER_LIST_SUGGESTIONS_SUCCESS = 'GET_USER_LIST_SUGGESTIONS_SUCCESS';
export const GET_USER_LIST_SUGGESTIONS_FAILURE = 'GET_USER_LIST_SUGGESTIONS_FAILURE';

export const CLEAN_USER_LIST_SUGGESTIONS = 'CLEAN_USER_LIST_SUGGESTIONS';

export const CREATE_TRANSACTION_REQUEST = 'CREATE_TRANSACTION_REQUEST';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_FAILURE = 'CREATE_TRANSACTION_FAILURE';

export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAILURE = 'GET_TRANSACTIONS_FAILURE';