export const GET_FILTERED_TRANSACTIONS_REQUEST = 'GET_FILTERED_TRANSACTIONS_REQUEST'
export const GET_FILTERED_TRANSACTIONS_SUCCESS = 'GET_FILTERED_TRANSACTIONS_SUCCESS';
export const GET_FILTERED_TRANSACTIONS_FAILURE = 'GET_FILTERED_TRANSACTIONS_FAILURE';

export const CLEAN_FILTERED_TRANSACTIONS = 'CLEAN_FILTERED_TRANSACTIONS';

export const CREATE_TRANSACTION_REQUEST = 'CREATE_TRANSACTION_REQUEST';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_FAILURE = 'CREATE_TRANSACTION_FAILURE';

export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAILURE = 'GET_TRANSACTIONS_FAILURE';